"""Tests for scripts/render-docs.py.

Covers the YAML → README fork-queue table render plus the marker-based
insertion machinery. The actual render-docs.py script lives outside the
``mempalace`` package, so tests load it via ``importlib``.
"""

from __future__ import annotations

import importlib.util
import subprocess
import sys
from pathlib import Path

import pytest


REPO_ROOT = Path(__file__).resolve().parents[1]
SCRIPT_PATH = REPO_ROOT / "scripts" / "render-docs.py"


def _load_render_module():
    spec = importlib.util.spec_from_file_location("_render_docs", SCRIPT_PATH)
    assert spec and spec.loader
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


@pytest.fixture(scope="module")
def render_docs():
    return _load_render_module()


def _make_manifest(entries: list[dict]) -> dict:
    return {
        "entries": entries,
        "merged_upstream": {
            "trim_after_days": 30,
            "notes": ["test note"],
            "entries": [],
        },
    }


# ── _queue_entries ────────────────────────────────────────────────────────


def test_queue_entries_excludes_merged_pr_state(render_docs):
    manifest = _make_manifest(
        [
            {"id": "a", "commit": "aaaaaaa", "summary": "Open", "pr": 1, "pr_state": "OPEN"},
            {"id": "b", "commit": "bbbbbbb", "summary": "Merged", "pr": 2, "pr_state": "MERGED"},
            {"id": "c", "commit": "ccccccc", "summary": "Closed", "pr": 3, "pr_state": "CLOSED"},
        ]
    )
    queue = render_docs._queue_entries(manifest)
    assert [e["id"] for e in queue] == ["a", "c"]


def test_queue_entries_includes_fork_only(render_docs):
    manifest = _make_manifest(
        [
            {"id": "fork-only", "commit": "1234567", "summary": "Local change"},
            {"id": "open", "commit": "abcdef0", "summary": "Has PR", "pr": 5, "pr_state": "OPEN"},
        ]
    )
    queue = render_docs._queue_entries(manifest)
    assert {e["id"] for e in queue} == {"fork-only", "open"}


# ── render_readme_queue ───────────────────────────────────────────────────


def test_render_readme_queue_basic_structure(render_docs):
    manifest = _make_manifest(
        [
            {"id": "a", "commit": "aaaaaaa", "summary": "First", "pr": 100, "pr_state": "OPEN"},
            {"id": "b", "commit": "bbbbbbb", "summary": "Second"},
        ]
    )
    table = render_docs.render_readme_queue(manifest)
    assert "| Description | Upstream PR | Fork commit |" in table
    assert "|---|---|---|" in table
    assert "generated by scripts/render-docs.py" in table
    data_rows = [
        ln for ln in table.splitlines() if ln.startswith("| First ") or ln.startswith("| Second ")
    ]
    assert len(data_rows) == 2


def test_render_readme_queue_pr_link_with_state(render_docs):
    manifest = _make_manifest(
        [{"id": "a", "commit": "aaaaaaa", "summary": "x", "pr": 1567, "pr_state": "OPEN"}]
    )
    table = render_docs.render_readme_queue(manifest)
    assert "[#1567](https://github.com/MemPalace/mempalace/pull/1567) (OPEN)" in table


def test_render_readme_queue_pr_link_without_state(render_docs):
    manifest = _make_manifest([{"id": "a", "commit": "aaaaaaa", "summary": "x", "pr": 10}])
    table = render_docs.render_readme_queue(manifest)
    assert "[#10](https://github.com/MemPalace/mempalace/pull/10)" in table
    assert "(OPEN)" not in table


def test_render_readme_queue_dash_when_no_pr(render_docs):
    manifest = _make_manifest([{"id": "fork", "commit": "1234567", "summary": "Fork only"}])
    table = render_docs.render_readme_queue(manifest)
    rows = [ln for ln in table.splitlines() if ln.startswith("| Fork only ")]
    assert len(rows) == 1
    assert " — " in rows[0]


def test_render_readme_queue_fork_commit_link(render_docs):
    manifest = _make_manifest([{"id": "a", "commit": "deadbee", "summary": "x"}])
    table = render_docs.render_readme_queue(manifest)
    assert "[`deadbee`](https://github.com/techempower-org/mempalace/commit/deadbee)" in table


def test_render_readme_queue_excludes_merged(render_docs):
    manifest = _make_manifest(
        [
            {"id": "a", "commit": "aaaaaaa", "summary": "Keep me", "pr": 1, "pr_state": "OPEN"},
            {"id": "b", "commit": "bbbbbbb", "summary": "Drop me", "pr": 2, "pr_state": "MERGED"},
        ]
    )
    table = render_docs.render_readme_queue(manifest)
    assert "Keep me" in table
    assert "Drop me" not in table


def test_render_readme_queue_escapes_pipe(render_docs):
    manifest = _make_manifest([{"id": "a", "commit": "aaaaaaa", "summary": "Has a | pipe"}])
    table = render_docs.render_readme_queue(manifest)
    assert r"Has a \| pipe" in table


def test_render_readme_queue_is_unnumbered(render_docs):
    """#473: the table carries NO row numbers.

    A leading row number meant one new entry renumbered every row below
    it, so any two concurrent PRs conflicted across the whole table
    rather than on one line. Rows keep manifest order; the ordinal was
    the only thing that made them interdependent.
    """
    manifest = _make_manifest(
        [{"id": str(i), "commit": f"{i:07d}", "summary": f"Entry {i}"} for i in range(1, 6)]
    )
    table = render_docs.render_readme_queue(manifest)
    for i in range(1, 6):
        assert f"| Entry {i} |" in table
        assert f"| {i} | Entry {i} " not in table


def test_render_readme_queue_keeps_order_while_excluding_merged(render_docs):
    manifest = _make_manifest(
        [
            {"id": "a", "commit": "aaaaaaa", "summary": "Keep1", "pr": 1, "pr_state": "OPEN"},
            {"id": "b", "commit": "bbbbbbb", "summary": "Skip", "pr": 2, "pr_state": "MERGED"},
            {"id": "c", "commit": "ccccccc", "summary": "Keep2", "pr": 3, "pr_state": "OPEN"},
        ]
    )
    table = render_docs.render_readme_queue(manifest)
    assert "Skip" not in table
    assert table.index("Keep1") < table.index("Keep2")


# ── replace_between_markers ───────────────────────────────────────────────


def test_replace_between_markers_round_trip(render_docs):
    before = "## Header\n<!-- BEGIN X -->\nold content\n<!-- END X -->\nfooter\n"
    out = render_docs.replace_between_markers(before, "<!-- BEGIN X -->", "<!-- END X -->", "NEW")
    assert "## Header\n" in out
    assert "NEW" in out
    assert "old content" not in out
    assert "footer" in out


def test_replace_between_markers_missing_begin(render_docs):
    with pytest.raises(ValueError, match="begin marker"):
        render_docs.replace_between_markers(
            "<!-- END X -->\n", "<!-- BEGIN X -->", "<!-- END X -->", "x"
        )


def test_replace_between_markers_missing_end(render_docs):
    with pytest.raises(ValueError, match="end marker"):
        render_docs.replace_between_markers(
            "<!-- BEGIN X -->\n", "<!-- BEGIN X -->", "<!-- END X -->", "x"
        )


def test_replace_between_markers_only_first_pair_replaced(render_docs):
    before = "<!-- BEGIN X -->\na\n<!-- END X -->\n<!-- BEGIN X -->\nb\n<!-- END X -->\n"
    out = render_docs.replace_between_markers(before, "<!-- BEGIN X -->", "<!-- END X -->", "Z")
    assert out.count("<!-- BEGIN X -->") == 2
    assert "Z" in out
    assert "b" in out


# ── render_readme integration ─────────────────────────────────────────────


def test_render_readme_replaces_markers(render_docs):
    manifest = _make_manifest(
        [{"id": "a", "commit": "aaaaaaa", "summary": "test row", "pr": 99, "pr_state": "OPEN"}]
    )
    existing = "# Title\n\n<!-- BEGIN FORK-QUEUE -->\nOLD\n<!-- END FORK-QUEUE -->\n\nEnd.\n"
    out = render_docs.render_readme(manifest, existing)
    assert "OLD" not in out
    assert "test row" in out
    assert "# Title" in out
    assert "End." in out
    assert "<!-- BEGIN FORK-QUEUE -->" in out
    assert "<!-- END FORK-QUEUE -->" in out


def test_render_readme_idempotent(render_docs):
    manifest = _make_manifest(
        [{"id": "a", "commit": "aaaaaaa", "summary": "row", "pr": 1, "pr_state": "OPEN"}]
    )
    existing = "<!-- BEGIN FORK-QUEUE -->\n<!-- END FORK-QUEUE -->\n"
    first = render_docs.render_readme(manifest, existing)
    second = render_docs.render_readme(manifest, first)
    assert first == second


# ── live YAML/README sanity checks ────────────────────────────────────────


def test_live_yaml_renders_without_error(render_docs):
    manifest = render_docs.load_manifest()
    table = render_docs.render_readme_queue(manifest)
    assert table.startswith("<!--")
    rows = [ln for ln in table.splitlines() if ln.startswith("| ") and "---" not in ln]
    assert len(rows) > 1, "expected a header plus data rows"


def test_live_readme_has_markers(render_docs):
    readme_text = render_docs.README_PATH.read_text()
    assert render_docs.README_BEGIN_MARKER in readme_text
    assert render_docs.README_END_MARKER in readme_text
    assert readme_text.index(render_docs.README_BEGIN_MARKER) < readme_text.index(
        render_docs.README_END_MARKER
    )


def test_live_readme_check_clean():
    """render-docs.py --check on the live tree should exit 0 (no drift)."""
    result = subprocess.run(
        [sys.executable, str(SCRIPT_PATH), "--check", "--target", "readme"],
        cwd=REPO_ROOT,
        capture_output=True,
        text=True,
    )
    assert result.returncode == 0, (
        f"README is stale — run scripts/render-docs.py --target readme to regenerate.\n"
        f"stdout: {result.stdout}\nstderr: {result.stderr}"
    )


# ── CLI surface ───────────────────────────────────────────────────────────


def test_cli_help_lists_readme_target():
    result = subprocess.run(
        [sys.executable, str(SCRIPT_PATH), "--help"],
        capture_output=True,
        text=True,
    )
    assert result.returncode == 0
    assert "readme" in result.stdout
    assert "changelog" in result.stdout
    assert "all" in result.stdout


def test_cli_target_all_accepts_literal():
    """--target all should not error at argparse level."""
    result = subprocess.run(
        [sys.executable, str(SCRIPT_PATH), "--check", "--target", "all"],
        cwd=REPO_ROOT,
        capture_output=True,
        text=True,
    )
    # 0 (clean) or 1 (drift) are both acceptable here — we just want to
    # confirm the literal is accepted by argparse. 2 would mean an
    # internal error.
    assert result.returncode in (0, 1), (
        f"unexpected exit code from --target all: {result.returncode}\n"
        f"stdout: {result.stdout}\nstderr: {result.stderr}"
    )


def test_unresolved_head_is_not_rendered_as_a_link(render_docs):
    """#476: `.../commit/HEAD` is a VALID GitHub URL that resolves to
    whatever is at main's tip.

    So an unresolved placeholder rendered as a link silently points at an
    unrelated commit while looking exactly like a real reference — a
    reader cannot tell them apart. Eight such links were live on main.
    Plain text is honest; a wrong link is not.
    """
    assert render_docs.commit_link("HEAD") == "`HEAD` — pending resolution"
    assert "commit/HEAD" not in render_docs.commit_link("HEAD")


def test_a_real_sha_is_still_linked(render_docs):
    out = render_docs.commit_link("abc1234")
    assert out == "[`abc1234`](https://github.com/techempower-org/mempalace/commit/abc1234)"
